// Content data for the math practice site, in English and Russian.
// build.js reads this file and generates one static HTML page per topic per language.
//
// IMPORTANT: SITE_URL is a placeholder until this site is deployed to a real domain.
// Update it (and re-run `npm run build`) once a real domain exists — it's used for
// canonical URLs, hreflang alternates, and the sitemap.
const SITE_URL = "https://example-placeholder.com";

const TOPICS = [
  {
    slug: "arithmetic",
    en: {
      navLabel: `Arithmetic`,
      pageTitle: `Arithmetic: Addition, Subtraction & Multiplication — Math Practice`,
      metaDescription: `Learn addition, subtraction, and multiplication with a simple example, then practice with instant feedback.`,
      h1: `Arithmetic: Addition, Subtraction & Multiplication`,
      ruleHtml: `<strong>Add</strong> to combine, <strong>subtract</strong> to find the difference, <strong>multiply</strong> to repeat-add.`,
      steps: [
        { type: "plain", text: `7 + 5 = 12` },
        { type: "plain", text: `9 &minus; 4 = 5` },
        { type: "plain", text: `6 &times; 3 = 18` },
      ],
      hintHtml: null,
    },
    ru: {
      navLabel: `Арифметика`,
      pageTitle: `Арифметика: сложение, вычитание и умножение — Практика по математике`,
      metaDescription: `Изучите сложение, вычитание и умножение на простом примере, а затем потренируйтесь с мгновенной проверкой ответов.`,
      h1: `Арифметика: сложение, вычитание и умножение`,
      ruleHtml: `<strong>Сложение</strong> объединяет числа, <strong>вычитание</strong> находит разницу, <strong>умножение</strong> — это многократное сложение.`,
      steps: [
        { type: "plain", text: `7 + 5 = 12` },
        { type: "plain", text: `9 &minus; 4 = 5` },
        { type: "plain", text: `6 &times; 3 = 18` },
      ],
      hintHtml: null,
    },
  },
  {
    slug: "negative-numbers",
    en: {
      navLabel: `Negative Numbers`,
      pageTitle: `Negative Numbers — Math Practice`,
      metaDescription: `Learn the rules for adding negative numbers with a simple worked example, then practice.`,
      h1: `Negative Numbers`,
      ruleHtml: `<strong>Same signs:</strong> add the numbers and keep the sign. <strong>Different signs:</strong> subtract the smaller from the bigger, and keep the sign of the bigger one.`,
      steps: [
        { type: "plain", text: `&minus;8 + 3` },
        { type: "note", text: `signs are different &rarr; subtract: 8 &minus; 3 = 5` },
        { type: "note", text: `keep the sign of the bigger number (&minus;8) &rarr; negative` },
        { type: "result", text: `= &minus;5` },
      ],
      hintHtml: null,
    },
    ru: {
      navLabel: `Отрицательные числа`,
      pageTitle: `Отрицательные числа — Практика по математике`,
      metaDescription: `Изучите правила сложения отрицательных чисел на простом примере, а затем потренируйтесь.`,
      h1: `Отрицательные числа`,
      ruleHtml: `<strong>Одинаковые знаки:</strong> сложите числа и сохраните знак. <strong>Разные знаки:</strong> вычтите меньшее число из большего и сохраните знак большего числа.`,
      steps: [
        { type: "plain", text: `&minus;8 + 3` },
        { type: "note", text: `знаки разные &rarr; вычитаем: 8 &minus; 3 = 5` },
        { type: "note", text: `сохраняем знак большего числа (&minus;8) &rarr; результат отрицательный` },
        { type: "result", text: `= &minus;5` },
      ],
      hintHtml: null,
    },
  },
  {
    slug: "order-of-operations",
    en: {
      navLabel: `Order of Operations`,
      pageTitle: `Order of Operations (PEMDAS) — Math Practice`,
      metaDescription: `Learn the correct order to solve math problems with multiple operations, then practice.`,
      h1: `Order of Operations`,
      ruleHtml: `When a problem has more than one operation, do things in this order: <strong>parentheses first</strong>, then <strong>multiplication</strong>, then <strong>addition/subtraction</strong>.`,
      steps: [
        { type: "plain", text: `2 + 3 &times; 4` },
        { type: "note", text: `multiply first &rarr; 3 &times; 4 = 12` },
        { type: "plain", text: `2 + 12` },
        { type: "result", text: `= 14` },
      ],
      hintHtml: null,
    },
    ru: {
      navLabel: `Порядок действий`,
      pageTitle: `Порядок действий — Практика по математике`,
      metaDescription: `Изучите правильный порядок решения примеров с несколькими действиями, а затем потренируйтесь.`,
      h1: `Порядок действий`,
      ruleHtml: `Если в примере несколько действий, выполняйте их в таком порядке: <strong>сначала скобки</strong>, потом <strong>умножение</strong>, потом <strong>сложение/вычитание</strong>.`,
      steps: [
        { type: "plain", text: `2 + 3 &times; 4` },
        { type: "note", text: `сначала умножаем &rarr; 3 &times; 4 = 12` },
        { type: "plain", text: `2 + 12` },
        { type: "result", text: `= 14` },
      ],
      hintHtml: null,
    },
  },
  {
    slug: "fractions",
    en: {
      navLabel: `Fractions`,
      pageTitle: `Fractions: Adding Fractions — Math Practice`,
      metaDescription: `Learn how to add fractions with different denominators step by step, then practice.`,
      h1: `Fractions: Adding Fractions`,
      ruleHtml: `To add fractions, they first need the <strong>same bottom number</strong> (denominator). Then just add the top numbers.`,
      steps: [
        { type: "plain", text: `1/4 + 1/6` },
        { type: "note", text: `give both fractions the same denominator &rarr; 12` },
        { type: "plain", text: `1/4 = 3/12` },
        { type: "plain", text: `1/6 = 2/12` },
        { type: "result", text: `3/12 + 2/12 = 5/12` },
      ],
      hintHtml: `Enter answers as a fraction, like <code>3/4</code>, or a whole number if it simplifies to one.`,
    },
    ru: {
      navLabel: `Дроби`,
      pageTitle: `Дроби: сложение дробей — Практика по математике`,
      metaDescription: `Узнайте, как складывать дроби с разными знаменателями, шаг за шагом, а затем потренируйтесь.`,
      h1: `Дроби: сложение дробей`,
      ruleHtml: `Чтобы сложить дроби, сначала нужно привести их к <strong>общему знаменателю</strong>. Затем просто сложите числители.`,
      steps: [
        { type: "plain", text: `1/4 + 1/6` },
        { type: "note", text: `приводим обе дроби к общему знаменателю &rarr; 12` },
        { type: "plain", text: `1/4 = 3/12` },
        { type: "plain", text: `1/6 = 2/12` },
        { type: "result", text: `3/12 + 2/12 = 5/12` },
      ],
      hintHtml: `Введите ответ в виде дроби, например <code>3/4</code>, или целым числом, если дробь сокращается до него.`,
    },
  },
  {
    slug: "gcf",
    en: {
      navLabel: `GCF`,
      pageTitle: `GCF: Greatest Common Factor — Math Practice`,
      metaDescription: `Learn how to find the greatest common factor of two numbers step by step, then practice.`,
      h1: `GCF: Greatest Common Factor`,
      ruleHtml: `The <strong>GCF</strong> of two numbers is the largest number that divides evenly into both of them.`,
      steps: [
        { type: "plain", text: `GCF(12, 18)` },
        { type: "note", text: `factors of 12: 1, 2, 3, 4, 6, 12` },
        { type: "note", text: `factors of 18: 1, 2, 3, 6, 9, 18` },
        { type: "note", text: `largest shared factor &rarr; 6` },
        { type: "result", text: `GCF(12, 18) = 6` },
      ],
      hintHtml: null,
    },
    ru: {
      navLabel: `НОД`,
      pageTitle: `НОД: наибольший общий делитель — Практика по математике`,
      metaDescription: `Узнайте, как найти наибольший общий делитель двух чисел, шаг за шагом, а затем потренируйтесь.`,
      h1: `НОД: наибольший общий делитель`,
      ruleHtml: `<strong>НОД</strong> двух чисел — это самое большое число, на которое оба числа делятся без остатка.`,
      steps: [
        { type: "plain", text: `НОД(12, 18)` },
        { type: "note", text: `делители 12: 1, 2, 3, 4, 6, 12` },
        { type: "note", text: `делители 18: 1, 2, 3, 6, 9, 18` },
        { type: "note", text: `самый большой общий делитель &rarr; 6` },
        { type: "result", text: `НОД(12, 18) = 6` },
      ],
      hintHtml: null,
    },
  },
  {
    slug: "lcm",
    en: {
      navLabel: `LCM`,
      pageTitle: `LCM: Least Common Multiple — Math Practice`,
      metaDescription: `Learn how to find the least common multiple of two numbers step by step, then practice.`,
      h1: `LCM: Least Common Multiple`,
      ruleHtml: `The <strong>LCM</strong> of two numbers is the smallest number that both of them divide into evenly. You can find it with: LCM = (a &times; b) &divide; GCF(a, b).`,
      steps: [
        { type: "plain", text: `LCM(4, 6)` },
        { type: "note", text: `GCF(4, 6) = 2` },
        { type: "plain", text: `LCM = (4 &times; 6) &divide; 2` },
        { type: "result", text: `= 12` },
      ],
      hintHtml: null,
    },
    ru: {
      navLabel: `НОК`,
      pageTitle: `НОК: наименьшее общее кратное — Практика по математике`,
      metaDescription: `Узнайте, как найти наименьшее общее кратное двух чисел, шаг за шагом, а затем потренируйтесь.`,
      h1: `НОК: наименьшее общее кратное`,
      ruleHtml: `<strong>НОК</strong> двух чисел — это самое маленькое число, которое делится на оба числа без остатка. Найти его можно так: НОК = (a &times; b) &divide; НОД(a, b).`,
      steps: [
        { type: "plain", text: `НОК(4, 6)` },
        { type: "note", text: `НОД(4, 6) = 2` },
        { type: "plain", text: `НОК = (4 &times; 6) &divide; 2` },
        { type: "result", text: `= 12` },
      ],
      hintHtml: null,
    },
  },
  {
    slug: "percentages",
    en: {
      navLabel: `Percentages`,
      pageTitle: `Percentages — Math Practice`,
      metaDescription: `Learn how to find a percentage of a number step by step, then practice.`,
      h1: `Percentages`,
      ruleHtml: `&quot;Percent&quot; means <strong>out of 100</strong>. To find a percent of a number, turn the percent into a decimal (divide by 100), then multiply.`,
      steps: [
        { type: "plain", text: `Find 20% of 50` },
        { type: "note", text: `20% = 20 &divide; 100 = 0.2` },
        { type: "plain", text: `0.2 &times; 50` },
        { type: "result", text: `= 10` },
      ],
      hintHtml: null,
    },
    ru: {
      navLabel: `Проценты`,
      pageTitle: `Проценты — Практика по математике`,
      metaDescription: `Узнайте, как находить процент от числа, шаг за шагом, а затем потренируйтесь.`,
      h1: `Проценты`,
      ruleHtml: `«Процент» означает <strong>«из ста»</strong>. Чтобы найти процент от числа, переведите процент в десятичную дробь (разделите на 100), а затем умножьте.`,
      steps: [
        { type: "plain", text: `Найти 20% от 50` },
        { type: "note", text: `20% = 20 &divide; 100 = 0,2` },
        { type: "plain", text: `0,2 &times; 50` },
        { type: "result", text: `= 10` },
      ],
      hintHtml: null,
    },
  },
  {
    slug: "average",
    en: {
      navLabel: `Average (Mean)`,
      pageTitle: `Average (Mean) — Math Practice`,
      metaDescription: `Learn how to calculate the average (mean) of a set of numbers step by step, then practice.`,
      h1: `Average (Mean)`,
      ruleHtml: `To find the <strong>average</strong>, add up all the numbers, then divide by how many numbers there are.`,
      steps: [
        { type: "plain", text: `4, 8, 6` },
        { type: "note", text: `add them: 4 + 8 + 6 = 18` },
        { type: "plain", text: `18 &divide; 3` },
        { type: "result", text: `= 6` },
      ],
      hintHtml: null,
    },
    ru: {
      navLabel: `Среднее арифметическое`,
      pageTitle: `Среднее арифметическое — Практика по математике`,
      metaDescription: `Узнайте, как вычислить среднее арифметическое набора чисел, шаг за шагом, а затем потренируйтесь.`,
      h1: `Среднее арифметическое`,
      ruleHtml: `Чтобы найти <strong>среднее арифметическое</strong>, сложите все числа, а затем разделите на их количество.`,
      steps: [
        { type: "plain", text: `4, 8, 6` },
        { type: "note", text: `складываем: 4 + 8 + 6 = 18` },
        { type: "plain", text: `18 &divide; 3` },
        { type: "result", text: `= 6` },
      ],
      hintHtml: null,
    },
  },
  {
    slug: "algebra",
    en: {
      navLabel: `Basic Algebra`,
      pageTitle: `Basic Algebra: Solving for x — Math Practice`,
      metaDescription: `Learn how to solve simple linear equations for x step by step, then practice.`,
      h1: `Basic Algebra: Solving for x`,
      ruleHtml: `To solve for x, get all the x terms on one side and all the plain numbers on the other. When a term crosses the equals sign, it changes to the <strong>opposite sign</strong> (+ becomes &minus;, and &minus; becomes +). Once only the x term is left, divide by the number in front of x.`,
      steps: [
        { type: "plain", text: `3x &minus; 5 = 10` },
        { type: "note", text: `move &minus;5 to the other side &rarr; it becomes +5` },
        { type: "plain", text: `3x = 10 + 5` },
        { type: "plain", text: `3x = 15` },
        { type: "note", text: `divide both sides by 3` },
        { type: "plain", text: `x = 15 / 3` },
        { type: "result", text: `x = 5` },
      ],
      hintHtml: null,
    },
    ru: {
      navLabel: `Основы алгебры`,
      pageTitle: `Основы алгебры: решаем уравнения с x — Практика по математике`,
      metaDescription: `Узнайте, как решать простые линейные уравнения с x, шаг за шагом, а затем потренируйтесь.`,
      h1: `Основы алгебры: решаем уравнения с x`,
      ruleHtml: `Чтобы найти x, соберите все члены с x на одной стороне, а обычные числа — на другой. Когда член переходит через знак равенства, он меняет знак на <strong>противоположный</strong> (+ становится &minus;, а &minus; становится +). Когда останется только член с x, разделите на число перед x.`,
      steps: [
        { type: "plain", text: `3x &minus; 5 = 10` },
        { type: "note", text: `переносим &minus;5 на другую сторону &rarr; он становится +5` },
        { type: "plain", text: `3x = 10 + 5` },
        { type: "plain", text: `3x = 15` },
        { type: "note", text: `делим обе части на 3` },
        { type: "plain", text: `x = 15 / 3` },
        { type: "result", text: `x = 5` },
      ],
      hintHtml: null,
    },
  },
  {
    slug: "functions",
    en: {
      navLabel: `Functions`,
      pageTitle: `Functions: Evaluating f(x) — Math Practice`,
      metaDescription: `Learn how to evaluate a function f(x) at a given value step by step, then practice.`,
      h1: `Functions: Evaluating f(x)`,
      ruleHtml: `A <strong>function</strong> f(x) is just a rule for turning an input x into an output. To evaluate it, put the given number everywhere you see x, then work it out.`,
      steps: [
        { type: "plain", text: `f(x) = 2x + 3` },
        { type: "note", text: `find f(4) &rarr; put 4 in place of x` },
        { type: "plain", text: `f(4) = 2(4) + 3` },
        { type: "plain", text: `f(4) = 8 + 3` },
        { type: "result", text: `f(4) = 11` },
      ],
      hintHtml: null,
    },
    ru: {
      navLabel: `Функции`,
      pageTitle: `Функции: вычисление f(x) — Практика по математике`,
      metaDescription: `Узнайте, как вычислить значение функции f(x) при заданном x, шаг за шагом, а затем потренируйтесь.`,
      h1: `Функции: вычисление f(x)`,
      ruleHtml: `<strong>Функция</strong> f(x) — это просто правило, превращающее число x в результат. Чтобы вычислить значение функции, подставьте данное число вместо x и посчитайте.`,
      steps: [
        { type: "plain", text: `f(x) = 2x + 3` },
        { type: "note", text: `найти f(4) &rarr; подставляем 4 вместо x` },
        { type: "plain", text: `f(4) = 2(4) + 3` },
        { type: "plain", text: `f(4) = 8 + 3` },
        { type: "result", text: `f(4) = 11` },
      ],
      hintHtml: null,
    },
  },
  {
    slug: "slope",
    en: {
      navLabel: `Slope of a Line`,
      pageTitle: `Slope of a Line — Math Practice`,
      metaDescription: `Learn how to find the slope between two points step by step, then practice.`,
      h1: `Slope of a Line`,
      ruleHtml: `<strong>Slope</strong> measures how steep a line is &mdash; &quot;rise over run.&quot; Given two points, slope = (y&#8322; &minus; y&#8321;) &divide; (x&#8322; &minus; x&#8321;).`,
      steps: [
        { type: "plain", text: `Points (1, 2) and (4, 11)` },
        { type: "note", text: `slope = (11 &minus; 2) &divide; (4 &minus; 1)` },
        { type: "plain", text: `9 &divide; 3` },
        { type: "result", text: `= 3` },
      ],
      hintHtml: null,
    },
    ru: {
      navLabel: `Наклон прямой`,
      pageTitle: `Наклон прямой — Практика по математике`,
      metaDescription: `Узнайте, как найти наклон прямой по двум точкам, шаг за шагом, а затем потренируйтесь.`,
      h1: `Наклон прямой`,
      ruleHtml: `<strong>Наклон</strong> показывает, насколько круто идёт прямая — «подъём делим на смещение». По двум точкам наклон = (y&#8322; &minus; y&#8321;) &divide; (x&#8322; &minus; x&#8321;).`,
      steps: [
        { type: "plain", text: `Точки (1, 2) и (4, 11)` },
        { type: "note", text: `наклон = (11 &minus; 2) &divide; (4 &minus; 1)` },
        { type: "plain", text: `9 &divide; 3` },
        { type: "result", text: `= 3` },
      ],
      hintHtml: null,
    },
  },
  {
    slug: "quadratic",
    en: {
      navLabel: `Quadratic Equations`,
      pageTitle: `Quadratic Equations: Solving ax² + bx + c = 0 — Math Practice`,
      metaDescription: `Learn how to solve a quadratic equation by factoring step by step, then practice.`,
      h1: `Quadratic Equations: Solving ax&sup2; + bx + c = 0`,
      ruleHtml: `A <strong>quadratic equation</strong> usually has two answers for x. One way to solve it is to find two numbers that <strong>multiply</strong> to c and <strong>add up</strong> to b, then split the equation into two simple ones.`,
      steps: [
        { type: "plain", text: `x&sup2; &minus; 5x + 6 = 0` },
        { type: "note", text: `find two numbers that multiply to 6 and add to &minus;5 &rarr; &minus;2 and &minus;3` },
        { type: "plain", text: `(x &minus; 2)(x &minus; 3) = 0` },
        { type: "note", text: `either part can be 0` },
        { type: "plain", text: `x &minus; 2 = 0 &nbsp; or &nbsp; x &minus; 3 = 0` },
        { type: "result", text: `x = 2 &nbsp; or &nbsp; x = 3` },
      ],
      hintHtml: `Enter both solutions separated by a comma, e.g. <code>2, 3</code> (either order is fine).`,
    },
    ru: {
      navLabel: `Квадратные уравнения`,
      pageTitle: `Квадратные уравнения: решаем ax² + bx + c = 0 — Практика по математике`,
      metaDescription: `Узнайте, как решить квадратное уравнение разложением на множители, шаг за шагом, а затем потренируйтесь.`,
      h1: `Квадратные уравнения: решаем ax&sup2; + bx + c = 0`,
      ruleHtml: `У <strong>квадратного уравнения</strong> обычно два решения для x. Один из способов — найти два числа, которые <strong>перемножаются</strong> в c и <strong>складываются</strong> в b, а затем разбить уравнение на два простых.`,
      steps: [
        { type: "plain", text: `x&sup2; &minus; 5x + 6 = 0` },
        { type: "note", text: `ищем два числа, которые дают 6 при умножении и &minus;5 при сложении &rarr; &minus;2 и &minus;3` },
        { type: "plain", text: `(x &minus; 2)(x &minus; 3) = 0` },
        { type: "note", text: `любой из множителей может быть равен 0` },
        { type: "plain", text: `x &minus; 2 = 0 &nbsp; или &nbsp; x &minus; 3 = 0` },
        { type: "result", text: `x = 2 &nbsp; или &nbsp; x = 3` },
      ],
      hintHtml: `Введите оба решения через запятую, например <code>2, 3</code> (порядок не важен).`,
    },
  },
  {
    slug: "parabola",
    en: {
      navLabel: `Parabola`,
      pageTitle: `Parabola: Finding the Vertex — Math Practice`,
      metaDescription: `Learn how to find the vertex of a parabola step by step, then practice.`,
      h1: `Parabola: Finding the Vertex`,
      ruleHtml: `A parabola is the curved graph of y = ax&sup2; + bx + c. Its highest or lowest point, the <strong>vertex</strong>, has an x-value you can find with a simple formula.`,
      steps: [
        { type: "plain", text: `y = x&sup2; &minus; 4x + 1` },
        { type: "note", text: `x = &minus;b &divide; (2 &times; a) &rarr; &minus;(&minus;4) &divide; (2 &times; 1)` },
        { type: "plain", text: `x = 4 &divide; 2` },
        { type: "result", text: `x = 2` },
      ],
      hintHtml: `Enter just the x-coordinate of the vertex (a whole number).`,
    },
    ru: {
      navLabel: `Парабола`,
      pageTitle: `Парабола: находим вершину — Практика по математике`,
      metaDescription: `Узнайте, как найти вершину параболы, шаг за шагом, а затем потренируйтесь.`,
      h1: `Парабола: находим вершину`,
      ruleHtml: `Парабола — это график вида y = ax&sup2; + bx + c. У её самой высокой или самой низкой точки, <strong>вершины</strong>, координату x можно найти по простой формуле.`,
      steps: [
        { type: "plain", text: `y = x&sup2; &minus; 4x + 1` },
        { type: "note", text: `x = &minus;b &divide; (2 &times; a) &rarr; &minus;(&minus;4) &divide; (2 &times; 1)` },
        { type: "plain", text: `x = 4 &divide; 2` },
        { type: "result", text: `x = 2` },
      ],
      hintHtml: `Введите только координату x вершины (целое число).`,
    },
  },
  {
    slug: "pythagorean",
    en: {
      navLabel: `Pythagorean Theorem`,
      pageTitle: `Pythagorean Theorem — Math Practice`,
      metaDescription: `Learn the Pythagorean theorem and how to find the hypotenuse step by step, then practice.`,
      h1: `Pythagorean Theorem`,
      ruleHtml: `For a right triangle with legs a and b and hypotenuse c: <strong>a&sup2; + b&sup2; = c&sup2;</strong>.`,
      steps: [
        { type: "plain", text: `legs 3 and 4` },
        { type: "note", text: `3&sup2; + 4&sup2; = 9 + 16 = 25` },
        { type: "plain", text: `c = &radic;25` },
        { type: "result", text: `c = 5` },
      ],
      hintHtml: null,
    },
    ru: {
      navLabel: `Теорема Пифагора`,
      pageTitle: `Теорема Пифагора — Практика по математике`,
      metaDescription: `Изучите теорему Пифагора и научитесь находить гипотенузу, шаг за шагом, а затем потренируйтесь.`,
      h1: `Теорема Пифагора`,
      ruleHtml: `Для прямоугольного треугольника с катетами a и b и гипотенузой c: <strong>a&sup2; + b&sup2; = c&sup2;</strong>.`,
      steps: [
        { type: "plain", text: `катеты 3 и 4` },
        { type: "note", text: `3&sup2; + 4&sup2; = 9 + 16 = 25` },
        { type: "plain", text: `c = &radic;25` },
        { type: "result", text: `c = 5` },
      ],
      hintHtml: null,
    },
  },
  {
    slug: "exponents",
    en: {
      navLabel: `Exponents`,
      pageTitle: `Exponents: Repeated Multiplication — Math Practice`,
      metaDescription: `Learn what exponents mean with a simple worked example, then practice.`,
      h1: `Exponents: Repeated Multiplication`,
      ruleHtml: `An <strong>exponent</strong> tells you how many times to multiply a number by itself.`,
      steps: [
        { type: "plain", text: `3&sup3; = ?` },
        { type: "note", text: `multiply 3 by itself 3 times` },
        { type: "plain", text: `3 &times; 3 &times; 3` },
        { type: "result", text: `= 27` },
      ],
      hintHtml: null,
    },
    ru: {
      navLabel: `Степени`,
      pageTitle: `Степени: многократное умножение — Практика по математике`,
      metaDescription: `Узнайте, что означает степень числа, на простом примере, а затем потренируйтесь.`,
      h1: `Степени: многократное умножение`,
      ruleHtml: `<strong>Степень</strong> показывает, сколько раз нужно умножить число само на себя.`,
      steps: [
        { type: "plain", text: `3&sup3; = ?` },
        { type: "note", text: `умножаем 3 само на себя 3 раза` },
        { type: "plain", text: `3 &times; 3 &times; 3` },
        { type: "result", text: `= 27` },
      ],
      hintHtml: null,
    },
  },
  {
    slug: "square-roots",
    en: {
      navLabel: `Square Roots`,
      pageTitle: `Square Roots — Math Practice`,
      metaDescription: `Learn what a square root is with a simple worked example, then practice.`,
      h1: `Square Roots`,
      ruleHtml: `A <strong>square root</strong> asks &quot;what number, times itself, gives this?&quot; The symbol is &radic;.`,
      steps: [
        { type: "plain", text: `&radic;49 = ?` },
        { type: "note", text: `what number times itself is 49?` },
        { type: "plain", text: `7 &times; 7 = 49` },
        { type: "result", text: `&radic;49 = 7` },
      ],
      hintHtml: null,
    },
    ru: {
      navLabel: `Квадратный корень`,
      pageTitle: `Квадратный корень — Практика по математике`,
      metaDescription: `Узнайте, что такое квадратный корень, на простом примере, а затем потренируйтесь.`,
      h1: `Квадратный корень`,
      ruleHtml: `<strong>Квадратный корень</strong> отвечает на вопрос «какое число, умноженное само на себя, даёт это число?». Обозначается символом &radic;.`,
      steps: [
        { type: "plain", text: `&radic;49 = ?` },
        { type: "note", text: `какое число, умноженное само на себя, даёт 49?` },
        { type: "plain", text: `7 &times; 7 = 49` },
        { type: "result", text: `&radic;49 = 7` },
      ],
      hintHtml: null,
    },
  },
  {
    slug: "absolute-value",
    en: {
      navLabel: `Absolute Value`,
      pageTitle: `Absolute Value — Math Practice`,
      metaDescription: `Learn what absolute value means with a simple worked example, then practice.`,
      h1: `Absolute Value`,
      ruleHtml: `<strong>Absolute value</strong> means &quot;distance from 0&quot; &mdash; so it's always positive (or zero), no matter the sign of the number inside.`,
      steps: [
        { type: "plain", text: `|&minus;7| = ?` },
        { type: "note", text: `distance from 0 to &minus;7 is 7` },
        { type: "result", text: `|&minus;7| = 7` },
      ],
      hintHtml: null,
    },
    ru: {
      navLabel: `Модуль числа`,
      pageTitle: `Модуль числа — Практика по математике`,
      metaDescription: `Узнайте, что такое модуль числа, на простом примере, а затем потренируйтесь.`,
      h1: `Модуль числа`,
      ruleHtml: `<strong>Модуль числа</strong> означает «расстояние до нуля» — поэтому он всегда положительный (или равен нулю), независимо от знака числа внутри.`,
      steps: [
        { type: "plain", text: `|&minus;7| = ?` },
        { type: "note", text: `расстояние от 0 до &minus;7 равно 7` },
        { type: "result", text: `|&minus;7| = 7` },
      ],
      hintHtml: null,
    },
  },
];

module.exports = { SITE_URL, TOPICS };
