// Content data for the math practice site, in English and Russian.
// build.js reads this file and generates one static HTML page per topic per language.
//
// SITE_URL is used for canonical URLs, hreflang alternates, and the sitemap.
// Update it (and re-run `npm run build`) if the domain ever changes.
const SITE_URL = "https://mathpractise.netlify.app";

const TOPICS = [
  {
    slug: "arithmetic",
    en: {
      navLabel: `Arithmetic`,
      pageTitle: `Arithmetic: Addition, Subtraction & Multiplication — Math Practice`,
      metaDescription: `Learn addition, subtraction, and multiplication with a simple example, then practice with instant feedback.`,
      h1: `Arithmetic: Addition, Subtraction & Multiplication`,
      hookHtml: `You're at the bazaar. You pick up 7 tomatoes, then grab 5 more &mdash; how many now? You started with 9 onions and used 4 in soup &mdash; how many are left? And you buy 3 trays of 6 eggs each &mdash; how many eggs in total?`,
      ruleHtml: `<strong>Add</strong> to combine, <strong>subtract</strong> to find the difference, <strong>multiply</strong> to repeat-add.`,
      oneLinerHtml: `In one line: add to combine, subtract to take away, multiply to repeat-add.`,
      steps: [
        { type: "plain", text: `7 + 5 = 12` },
        { type: "plain", text: `9 &minus; 4 = 5` },
        { type: "plain", text: `6 &times; 3 = 18` },
      ],
      trapHtml: `A common mistake is mixing up the order in subtraction &mdash; 9 &minus; 4 is not the same as 4 &minus; 9. Always subtract the second number from the first, not the other way around.`,
      whyItMattersHtml: `These three moves are the foundation for every other topic on this site &mdash; you'll use them constantly, from shopping to cooking to counting anything.`,
      hintHtml: null,
    },
    ru: {
      navLabel: `Арифметика`,
      pageTitle: `Арифметика: сложение, вычитание и умножение — Практика по математике`,
      metaDescription: `Изучите сложение, вычитание и умножение на простом примере, а затем потренируйтесь с мгновенной проверкой ответов.`,
      h1: `Арифметика: сложение, вычитание и умножение`,
      hookHtml: `Вы на базаре. Берёте 7 помидоров, потом ещё 5 &mdash; сколько теперь? У вас было 9 луковиц, 4 ушли в суп &mdash; сколько осталось? И вы покупаете 3 лотка по 6 яиц &mdash; сколько яиц всего?`,
      ruleHtml: `<strong>Сложение</strong> объединяет числа, <strong>вычитание</strong> находит разницу, <strong>умножение</strong> — это многократное сложение.`,
      oneLinerHtml: `Одной фразой: сложение объединяет, вычитание убирает, умножение — это многократное сложение.`,
      steps: [
        { type: "plain", text: `7 + 5 = 12` },
        { type: "plain", text: `9 &minus; 4 = 5` },
        { type: "plain", text: `6 &times; 3 = 18` },
      ],
      trapHtml: `Частая ошибка — перепутать порядок при вычитании: 9 &minus; 4 не то же самое, что 4 &minus; 9. Всегда вычитайте второе число из первого, а не наоборот.`,
      whyItMattersHtml: `Эти три действия — основа всех остальных тем на этом сайте: они пригодятся везде, от покупок до готовки по рецепту.`,
      hintHtml: null,
    },
  },
  {
    slug: "negative-numbers",
    en: {
      navLabel: `Negative Numbers`,
      pageTitle: `Negative Numbers — Math Practice`,
      metaDescription: `Learn the rules for adding negative numbers with a simple worked example, then practice.`,
      h1: `Negative Numbers`,
      hookHtml: `Your bank balance is 8,000 so'm in debt (&minus;8,000), then a friend pays you back 3,000 so'm. What's your balance now?`,
      ruleHtml: `<strong>Same signs:</strong> add the numbers and keep the sign. <strong>Different signs:</strong> subtract the smaller from the bigger, and keep the sign of the bigger one.`,
      oneLinerHtml: `In one line: same signs, add and keep; different signs, subtract and keep the bigger's sign.`,
      steps: [
        { type: "plain", text: `&minus;8 + 3` },
        { type: "note", text: `signs are different &rarr; subtract: 8 &minus; 3 = 5` },
        { type: "note", text: `keep the sign of the bigger number (&minus;8) &rarr; negative` },
        { type: "result", text: `= &minus;5` },
      ],
      trapHtml: `The most common mistake is just adding 8 and 3 to get 11 and forgetting the sign entirely &mdash; always check whether the signs are the same or different first.`,
      whyItMattersHtml: `Negative numbers show up anywhere something can go below zero &mdash; debt, temperature, elevation below sea level.`,
      hintHtml: null,
    },
    ru: {
      navLabel: `Отрицательные числа`,
      pageTitle: `Отрицательные числа — Практика по математике`,
      metaDescription: `Изучите правила сложения отрицательных чисел на простом примере, а затем потренируйтесь.`,
      h1: `Отрицательные числа`,
      hookHtml: `Ваш баланс — минус 8 000 сум (долг), а друг возвращает вам 3 000 сум. Какой у вас баланс теперь?`,
      ruleHtml: `<strong>Одинаковые знаки:</strong> сложите числа и сохраните знак. <strong>Разные знаки:</strong> вычтите меньшее число из большего и сохраните знак большего числа.`,
      oneLinerHtml: `Одной фразой: одинаковые знаки — складываем и сохраняем знак; разные знаки — вычитаем и берём знак большего числа.`,
      steps: [
        { type: "plain", text: `&minus;8 + 3` },
        { type: "note", text: `знаки разные &rarr; вычитаем: 8 &minus; 3 = 5` },
        { type: "note", text: `сохраняем знак большего числа (&minus;8) &rarr; результат отрицательный` },
        { type: "result", text: `= &minus;5` },
      ],
      trapHtml: `Самая частая ошибка — просто сложить 8 и 3, получив 11, и забыть про знак. Сначала всегда проверяйте, одинаковые знаки или разные.`,
      whyItMattersHtml: `Отрицательные числа появляются везде, где что-то может быть ниже нуля — долг, температура, высота ниже уровня моря.`,
      hintHtml: null,
    },
  },
  {
    slug: "order-of-operations",
    en: {
      navLabel: `Order of Operations`,
      pageTitle: `Order of Operations (PEMDAS) — Math Practice`,
      metaDescription: `Learn the correct order to solve math problems with multiple operations, then practice.`,
      h1: `Order of Operations`,
      hookHtml: `You have 2,000 so'm saved, plus you work 3 shifts earning 4,000 so'm each. How much do you have in total?`,
      ruleHtml: `When a problem has more than one operation, do things in this order: <strong>parentheses first</strong>, then <strong>multiplication</strong>, then <strong>addition/subtraction</strong>.`,
      oneLinerHtml: `In one line: multiply (and parentheses) before you add or subtract.`,
      steps: [
        { type: "plain", text: `2 + 3 &times; 4` },
        { type: "note", text: `multiply first &rarr; 3 &times; 4 = 12` },
        { type: "plain", text: `2 + 12` },
        { type: "result", text: `= 14` },
      ],
      trapHtml: `A common mistake is working strictly left to right and getting 2 + 3 = 5, then 5 &times; 4 = 20 &mdash; the wrong order. Multiplication always happens before addition, no matter which comes first on the page.`,
      whyItMattersHtml: `Without an agreed order, the same expression could mean different things to different people &mdash; this rule keeps math consistent for everyone.`,
      hintHtml: null,
    },
    ru: {
      navLabel: `Порядок действий`,
      pageTitle: `Порядок действий — Практика по математике`,
      metaDescription: `Изучите правильный порядок решения примеров с несколькими действиями, а затем потренируйтесь.`,
      h1: `Порядок действий`,
      hookHtml: `У вас есть 2 000 сум, и вы отработали 3 смены по 4 000 сум каждая. Сколько у вас денег всего?`,
      ruleHtml: `Если в примере несколько действий, выполняйте их в таком порядке: <strong>сначала скобки</strong>, потом <strong>умножение</strong>, потом <strong>сложение/вычитание</strong>.`,
      oneLinerHtml: `Одной фразой: умножение (и скобки) выполняются раньше сложения и вычитания.`,
      steps: [
        { type: "plain", text: `2 + 3 &times; 4` },
        { type: "note", text: `сначала умножаем &rarr; 3 &times; 4 = 12` },
        { type: "plain", text: `2 + 12` },
        { type: "result", text: `= 14` },
      ],
      trapHtml: `Частая ошибка — считать строго слева направо: 2 + 3 = 5, потом 5 &times; 4 = 20. Это неверно — умножение всегда выполняется раньше сложения, независимо от порядка записи.`,
      whyItMattersHtml: `Без единого правила одно и то же выражение можно было бы понять по-разному — этот порядок делает математику одинаковой для всех.`,
      hintHtml: null,
    },
  },
  {
    slug: "fractions",
    en: {
      navLabel: `Fractions`,
      pageTitle: `Fractions: Adding Fractions — Math Practice`,
      metaDescription: `Learn how to add fractions with different denominators step by step, then practice.`,
      h1: `Fractions: Adding Fractions`,
      hookHtml: `You eat 1/4 of a pizza, then 1/6 of another pizza. How much pizza did you eat in total?`,
      ruleHtml: `To add fractions, they first need the <strong>same bottom number</strong> (denominator). Then just add the top numbers.`,
      oneLinerHtml: `In one line: same bottom number first, then add the tops.`,
      steps: [
        { type: "plain", text: `1/4 + 1/6` },
        { type: "note", text: `give both fractions the same denominator &rarr; 12` },
        { type: "plain", text: `1/4 = 3/12` },
        { type: "plain", text: `1/6 = 2/12` },
        { type: "result", text: `3/12 + 2/12 = 5/12` },
      ],
      trapHtml: `The most common mistake is adding the denominators too &mdash; 1/4 + 1/6 is NOT 2/10. You can only add the top numbers once the bottom numbers match.`,
      whyItMattersHtml: `Fractions come up anywhere something is split into parts &mdash; recipes, time, money, sharing.`,
      hintHtml: `Enter answers as a fraction, like <code>3/4</code>, or a whole number if it simplifies to one.`,
    },
    ru: {
      navLabel: `Дроби`,
      pageTitle: `Дроби: сложение дробей — Практика по математике`,
      metaDescription: `Узнайте, как складывать дроби с разными знаменателями, шаг за шагом, а затем потренируйтесь.`,
      h1: `Дроби: сложение дробей`,
      hookHtml: `Вы съели 1/4 одной пиццы и 1/6 другой. Сколько пиццы вы съели всего?`,
      ruleHtml: `Чтобы сложить дроби, сначала нужно привести их к <strong>общему знаменателю</strong>. Затем просто сложите числители.`,
      oneLinerHtml: `Одной фразой: сначала общий знаменатель, потом складываем числители.`,
      steps: [
        { type: "plain", text: `1/4 + 1/6` },
        { type: "note", text: `приводим обе дроби к общему знаменателю &rarr; 12` },
        { type: "plain", text: `1/4 = 3/12` },
        { type: "plain", text: `1/6 = 2/12` },
        { type: "result", text: `3/12 + 2/12 = 5/12` },
      ],
      trapHtml: `Частая ошибка — сложить и знаменатели тоже: 1/4 + 1/6 — это НЕ 2/10. Числители можно складывать только после того, как знаменатели совпали.`,
      whyItMattersHtml: `Дроби встречаются везде, где что-то делится на части — рецепты, время, деньги, доли.`,
      hintHtml: `Введите ответ в виде дроби, например <code>3/4</code>, или целым числом, если дробь сокращается до него.`,
    },
  },
  {
    slug: "gcf",
    en: {
      navLabel: `GCF`,
      pageTitle: `GCF: Greatest Common Factor — Math Practice`,
      metaDescription: `Learn how to find the greatest common factor of two numbers step by step, then practice.`,
      h1: `GCF: Greatest Common Factor`,
      hookHtml: `You have 12 samsa and 18 pastries and want to arrange them on identical trays with none left over, using the biggest tray size possible. How many should go on each tray?`,
      ruleHtml: `The <strong>GCF</strong> of two numbers is the largest number that divides evenly into both of them.`,
      oneLinerHtml: `In one line: list the factors of both, then pick the biggest one they share.`,
      steps: [
        { type: "plain", text: `GCF(12, 18)` },
        { type: "note", text: `factors of 12: 1, 2, 3, 4, 6, 12` },
        { type: "note", text: `factors of 18: 1, 2, 3, 6, 9, 18` },
        { type: "note", text: `largest shared factor &rarr; 6` },
        { type: "result", text: `GCF(12, 18) = 6` },
      ],
      trapHtml: `A common mistake is picking a shared factor that isn't the largest &mdash; 12 and 18 also share 2 and 3, but the GCF is the biggest one they share, 6.`,
      whyItMattersHtml: `The GCF is what lets you simplify fractions and split things into the fewest, most even groups.`,
      hintHtml: null,
    },
    ru: {
      navLabel: `НОД`,
      pageTitle: `НОД: наибольший общий делитель — Практика по математике`,
      metaDescription: `Узнайте, как найти наибольший общий делитель двух чисел, шаг за шагом, а затем потренируйтесь.`,
      h1: `НОД: наибольший общий делитель`,
      hookHtml: `У вас 12 самсы и 18 пирожков, и вы хотите разложить их на одинаковые подносы без остатка, используя подносы самого большого возможного размера. Сколько должно быть на каждом подносе?`,
      ruleHtml: `<strong>НОД</strong> двух чисел — это самое большое число, на которое оба числа делятся без остатка.`,
      oneLinerHtml: `Одной фразой: выпишите делители обоих чисел и возьмите самый большой общий.`,
      steps: [
        { type: "plain", text: `НОД(12, 18)` },
        { type: "note", text: `делители 12: 1, 2, 3, 4, 6, 12` },
        { type: "note", text: `делители 18: 1, 2, 3, 6, 9, 18` },
        { type: "note", text: `самый большой общий делитель &rarr; 6` },
        { type: "result", text: `НОД(12, 18) = 6` },
      ],
      trapHtml: `Частая ошибка — взять общий делитель, но не самый большой: у 12 и 18 есть общие делители 2 и 3, но НОД — это 6, самый большой из них.`,
      whyItMattersHtml: `НОД помогает сокращать дроби и делить предметы на самые ровные и малочисленные группы.`,
      hintHtml: null,
    },
  },
  {
    slug: "lcm",
    en: {
      navLabel: `LCM`,
      pageTitle: `LCM: Least Common Multiple — Math Practice`,
      metaDescription: `Learn how to find the least common multiple of two numbers step by step, then practice.`,
      h1: `LCM: Least Common Multiple`,
      hookHtml: `One bus leaves every 4 minutes, another every 6 minutes. They just left together &mdash; how many minutes until they leave together again?`,
      ruleHtml: `The <strong>LCM</strong> of two numbers is the smallest number that both of them divide into evenly. You can find it with: LCM = (a &times; b) &divide; GCF(a, b).`,
      oneLinerHtml: `In one line: multiply the numbers, then divide by their GCF.`,
      steps: [
        { type: "plain", text: `LCM(4, 6)` },
        { type: "note", text: `GCF(4, 6) = 2` },
        { type: "plain", text: `LCM = (4 &times; 6) &divide; 2` },
        { type: "result", text: `= 12` },
      ],
      trapHtml: `A common mistake is just multiplying the two numbers (4 &times; 6 = 24) and stopping there &mdash; that's a common multiple, but not the smallest one. Always divide by the GCF to shrink it down.`,
      whyItMattersHtml: `The LCM is exactly how you find a common denominator when adding fractions, or figure out when repeating events line up.`,
      hintHtml: null,
    },
    ru: {
      navLabel: `НОК`,
      pageTitle: `НОК: наименьшее общее кратное — Практика по математике`,
      metaDescription: `Узнайте, как найти наименьшее общее кратное двух чисел, шаг за шагом, а затем потренируйтесь.`,
      h1: `НОК: наименьшее общее кратное`,
      hookHtml: `Один автобус отправляется каждые 4 минуты, другой — каждые 6 минут. Они только что отправились вместе. Через сколько минут они снова отправятся одновременно?`,
      ruleHtml: `<strong>НОК</strong> двух чисел — это самое маленькое число, которое делится на оба числа без остатка. Найти его можно так: НОК = (a &times; b) &divide; НОД(a, b).`,
      oneLinerHtml: `Одной фразой: перемножьте числа и разделите на их НОД.`,
      steps: [
        { type: "plain", text: `НОК(4, 6)` },
        { type: "note", text: `НОД(4, 6) = 2` },
        { type: "plain", text: `НОК = (4 &times; 6) &divide; 2` },
        { type: "result", text: `= 12` },
      ],
      trapHtml: `Частая ошибка — просто перемножить числа (4 &times; 6 = 24) и остановиться на этом. Это общее кратное, но не наименьшее — обязательно разделите на НОД.`,
      whyItMattersHtml: `НОК — это именно то, что нужно для приведения дробей к общему знаменателю или для расчёта, когда совпадут повторяющиеся события.`,
      hintHtml: null,
    },
  },
  {
    slug: "percentages",
    en: {
      navLabel: `Percentages`,
      pageTitle: `Percentages — Math Practice`,
      metaDescription: `Learn how to find a percentage of a number step by step, then practice.`,
      h1: `Percentages`,
      hookHtml: `A jacket costs 50,000 so'm. It's 20% off &mdash; how much do you save?`,
      ruleHtml: `&quot;Percent&quot; means <strong>out of 100</strong>. To find a percent of a number, turn the percent into a decimal (divide by 100), then multiply.`,
      oneLinerHtml: `In one line: turn the % into a decimal, then multiply.`,
      steps: [
        { type: "plain", text: `Find 20% of 50,000` },
        { type: "note", text: `20% = 20 &divide; 100 = 0.2` },
        { type: "plain", text: `0.2 &times; 50,000` },
        { type: "result", text: `= 10,000 so'm saved` },
      ],
      trapHtml: `A common mistake is multiplying by 20 instead of 0.2 &mdash; that gives 1,000,000, way more than the jacket even costs. If your answer is bigger than the number you started with, you forgot to convert the percent first.`,
      whyItMattersHtml: `You'll use this constantly &mdash; discounts, tips, interest, exam scores.`,
      hintHtml: null,
    },
    ru: {
      navLabel: `Проценты`,
      pageTitle: `Проценты — Практика по математике`,
      metaDescription: `Узнайте, как находить процент от числа, шаг за шагом, а затем потренируйтесь.`,
      h1: `Проценты`,
      hookHtml: `Куртка стоит 50 000 сум. На неё скидка 20% — сколько вы сэкономите?`,
      ruleHtml: `«Процент» означает <strong>«из ста»</strong>. Чтобы найти процент от числа, переведите процент в десятичную дробь (разделите на 100), а затем умножьте.`,
      oneLinerHtml: `Одной фразой: переведите % в десятичную дробь, затем умножьте.`,
      steps: [
        { type: "plain", text: `Найти 20% от 50 000` },
        { type: "note", text: `20% = 20 &divide; 100 = 0,2` },
        { type: "plain", text: `0,2 &times; 50 000` },
        { type: "result", text: `= 10 000 сум сэкономлено` },
      ],
      trapHtml: `Частая ошибка — умножить на 20 вместо 0,2: получится 1 000 000, что намного больше стоимости самой куртки. Если ответ больше исходного числа, вы забыли перевести процент в десятичную дробь.`,
      whyItMattersHtml: `Это пригодится постоянно — скидки, чаевые, проценты по вкладу, оценки на экзаменах.`,
      hintHtml: null,
    },
  },
  {
    slug: "average",
    en: {
      navLabel: `Average (Mean)`,
      pageTitle: `Average (Mean) — Math Practice`,
      metaDescription: `Learn how to calculate the average (mean) of a set of numbers step by step, then practice.`,
      h1: `Average (Mean)`,
      hookHtml: `You scored 4, 8, and 6 points in three mini-games at a fair. What's your average score?`,
      ruleHtml: `To find the <strong>average</strong>, add up all the numbers, then divide by how many numbers there are.`,
      oneLinerHtml: `In one line: add them all up, divide by how many there are.`,
      steps: [
        { type: "plain", text: `4, 8, 6` },
        { type: "note", text: `add them: 4 + 8 + 6 = 18` },
        { type: "plain", text: `18 &divide; 3` },
        { type: "result", text: `= 6` },
      ],
      trapHtml: `A common mistake is dividing by the wrong count &mdash; forgetting one of the numbers, or dividing by 2 instead of 3. Always count exactly how many numbers you added.`,
      whyItMattersHtml: `Averages summarize a whole set of numbers with one &mdash; test scores, prices, ratings, sports stats.`,
      hintHtml: null,
    },
    ru: {
      navLabel: `Среднее арифметическое`,
      pageTitle: `Среднее арифметическое — Практика по математике`,
      metaDescription: `Узнайте, как вычислить среднее арифметическое набора чисел, шаг за шагом, а затем потренируйтесь.`,
      h1: `Среднее арифметическое`,
      hookHtml: `Вы набрали 4, 8 и 6 очков в трёх мини-играх на ярмарке. Какой у вас средний результат?`,
      ruleHtml: `Чтобы найти <strong>среднее арифметическое</strong>, сложите все числа, а затем разделите на их количество.`,
      oneLinerHtml: `Одной фразой: сложите все числа и разделите на их количество.`,
      steps: [
        { type: "plain", text: `4, 8, 6` },
        { type: "note", text: `складываем: 4 + 8 + 6 = 18` },
        { type: "plain", text: `18 &divide; 3` },
        { type: "result", text: `= 6` },
      ],
      trapHtml: `Частая ошибка — разделить не на то количество: забыть одно число или разделить на 2 вместо 3. Всегда считайте, сколько чисел вы сложили.`,
      whyItMattersHtml: `Среднее одним числом описывает целый набор данных — оценки, цены, рейтинги, спортивную статистику.`,
      hintHtml: null,
    },
  },
  {
    slug: "algebra",
    en: {
      navLabel: `Basic Algebra`,
      pageTitle: `Basic Algebra: Solving for x — Math Practice`,
      metaDescription: `Learn how to solve simple linear equations for x step by step, then practice.`,
      h1: `Basic Algebra: Solving for x`,
      hookHtml: `You buy 3 identical notebooks, use a 5,000 so'm discount coupon, and pay 10,000 so'm total. How much was one notebook before the discount?`,
      ruleHtml: `To solve for x, get all the x terms on one side and all the plain numbers on the other. When a term crosses the equals sign, it changes to the <strong>opposite sign</strong> (+ becomes &minus;, and &minus; becomes +). Once only the x term is left, divide by the number in front of x.`,
      oneLinerHtml: `In one line: move it across, flip the sign, then divide.`,
      steps: [
        { type: "plain", text: `3x &minus; 5 = 10` },
        { type: "note", text: `move &minus;5 to the other side &rarr; it becomes +5` },
        { type: "plain", text: `3x = 10 + 5` },
        { type: "plain", text: `3x = 15` },
        { type: "note", text: `divide both sides by 3` },
        { type: "plain", text: `x = 15 / 3` },
        { type: "result", text: `x = 5 (so'm, in thousands)` },
      ],
      trapHtml: `The #1 mistake is forgetting to flip the sign &mdash; writing 3x = 10 &minus; 5 instead of 3x = 10 + 5. The moment a term crosses the equals sign, its sign flips.`,
      whyItMattersHtml: `This move is behind almost every word problem &mdash; splitting bills, adjusting prices, figuring out how many of something you can afford.`,
      hintHtml: null,
    },
    ru: {
      navLabel: `Основы алгебры`,
      pageTitle: `Основы алгебры: решаем уравнения с x — Практика по математике`,
      metaDescription: `Узнайте, как решать простые линейные уравнения с x, шаг за шагом, а затем потренируйтесь.`,
      h1: `Основы алгебры: решаем уравнения с x`,
      hookHtml: `Вы покупаете 3 одинаковых тетради, используете купон на скидку 5 000 сум и платите 10 000 сум. Сколько стоила одна тетрадь до скидки?`,
      ruleHtml: `Чтобы найти x, соберите все члены с x на одной стороне, а обычные числа — на другой. Когда член переходит через знак равенства, он меняет знак на <strong>противоположный</strong> (+ становится &minus;, а &minus; становится +). Когда останется только член с x, разделите на число перед x.`,
      oneLinerHtml: `Одной фразой: переносим — знак меняется, затем делим.`,
      steps: [
        { type: "plain", text: `3x &minus; 5 = 10` },
        { type: "note", text: `переносим &minus;5 на другую сторону &rarr; он становится +5` },
        { type: "plain", text: `3x = 10 + 5` },
        { type: "plain", text: `3x = 15` },
        { type: "note", text: `делим обе части на 3` },
        { type: "plain", text: `x = 15 / 3` },
        { type: "result", text: `x = 5 (тысяч сум)` },
      ],
      trapHtml: `Самая частая ошибка — забыть поменять знак при переносе: писать 3x = 10 &minus; 5 вместо 3x = 10 + 5. В момент, когда член переходит через знак равенства, его знак меняется на противоположный.`,
      whyItMattersHtml: `Этот приём лежит в основе почти любой текстовой задачи — деление счёта, изменение цены, расчёт того, сколько вы можете себе позволить.`,
      hintHtml: null,
    },
  },
  {
    slug: "functions",
    en: {
      navLabel: `Functions`,
      pageTitle: `Functions: Evaluating f(x) — Math Practice`,
      metaDescription: `Learn how to evaluate a function f(x) at a given value step by step, then practice.`,
      h1: `Functions: Evaluating f(x)`,
      hookHtml: `A taxi charges a 3,000 so'm base fee plus 2,000 so'm per kilometer. If f(x) = 2x + 3 gives the fare (in thousands) for x kilometers, what's the fare for a 4 km ride?`,
      ruleHtml: `A <strong>function</strong> f(x) is just a rule for turning an input x into an output. To evaluate it, put the given number everywhere you see x, then work it out.`,
      oneLinerHtml: `In one line: swap x for the given number, then simplify.`,
      steps: [
        { type: "plain", text: `f(x) = 2x + 3` },
        { type: "note", text: `find f(4) &rarr; put 4 in place of x` },
        { type: "plain", text: `f(4) = 2(4) + 3` },
        { type: "plain", text: `f(4) = 8 + 3` },
        { type: "result", text: `f(4) = 11` },
      ],
      trapHtml: `A common mistake is only replacing x in one spot when it appears more than once, or adding before multiplying. Replace every x first, then follow the order of operations.`,
      whyItMattersHtml: `Functions describe how one thing depends on another &mdash; like how a taxi fare depends on distance, or how your pay depends on hours worked.`,
      hintHtml: null,
    },
    ru: {
      navLabel: `Функции`,
      pageTitle: `Функции: вычисление f(x) — Практика по математике`,
      metaDescription: `Узнайте, как вычислить значение функции f(x) при заданном x, шаг за шагом, а затем потренируйтесь.`,
      h1: `Функции: вычисление f(x)`,
      hookHtml: `Такси берёт базовую плату 3 000 сум плюс 2 000 сум за каждый километр. Если f(x) = 2x + 3 — это стоимость поездки (в тысячах сум) за x километров, сколько будет стоить поездка на 4 км?`,
      ruleHtml: `<strong>Функция</strong> f(x) — это просто правило, превращающее число x в результат. Чтобы вычислить значение функции, подставьте данное число вместо x и посчитайте.`,
      oneLinerHtml: `Одной фразой: подставьте число вместо x, затем упростите.`,
      steps: [
        { type: "plain", text: `f(x) = 2x + 3` },
        { type: "note", text: `найти f(4) &rarr; подставляем 4 вместо x` },
        { type: "plain", text: `f(4) = 2(4) + 3` },
        { type: "plain", text: `f(4) = 8 + 3` },
        { type: "result", text: `f(4) = 11` },
      ],
      trapHtml: `Частая ошибка — заменить x только в одном месте, если он встречается несколько раз, или сложить раньше, чем умножить. Сначала замените каждый x, потом соблюдайте порядок действий.`,
      whyItMattersHtml: `Функции показывают, как одна величина зависит от другой — например, как стоимость поездки зависит от расстояния или зарплата от часов работы.`,
      hintHtml: null,
    },
  },
  {
    slug: "slope",
    en: {
      navLabel: `Slope of a Line`,
      pageTitle: `Slope of a Line — Math Practice`,
      metaDescription: `Learn how to find the slope between two points step by step, then practice.`,
      h1: `Slope of a Line`,
      hookHtml: `A hiking trail is at 2 meters of elevation at the 1 km mark, and by the 4 km mark it's at 11 meters. How steep is the trail, on average?`,
      ruleHtml: `<strong>Slope</strong> measures how steep a line is &mdash; &quot;rise over run.&quot; Given two points, slope = (y&#8322; &minus; y&#8321;) &divide; (x&#8322; &minus; x&#8321;).`,
      oneLinerHtml: `In one line: rise over run &mdash; change in y divided by change in x.`,
      steps: [
        { type: "plain", text: `Points (1, 2) and (4, 11)` },
        { type: "note", text: `slope = (11 &minus; 2) &divide; (4 &minus; 1)` },
        { type: "plain", text: `9 &divide; 3` },
        { type: "result", text: `= 3` },
      ],
      trapHtml: `A common mistake is subtracting the coordinates in mismatched order &mdash; doing (11 &minus; 2) for y but then (1 &minus; 4) instead of (4 &minus; 1) for x. Always subtract in the same order for both x and y.`,
      whyItMattersHtml: `Slope measures rate of change &mdash; speed, steepness, growth &mdash; one of the most useful ideas in math and science.`,
      hintHtml: null,
    },
    ru: {
      navLabel: `Наклон прямой`,
      pageTitle: `Наклон прямой — Практика по математике`,
      metaDescription: `Узнайте, как найти наклон прямой по двум точкам, шаг за шагом, а затем потренируйтесь.`,
      h1: `Наклон прямой`,
      hookHtml: `Туристическая тропа на отметке 1 км имеет высоту 2 метра, а на отметке 4 км — уже 11 метров. Насколько крутая тропа в среднем?`,
      ruleHtml: `<strong>Наклон</strong> показывает, насколько круто идёт прямая — «подъём делим на смещение». По двум точкам наклон = (y&#8322; &minus; y&#8321;) &divide; (x&#8322; &minus; x&#8321;).`,
      oneLinerHtml: `Одной фразой: подъём делим на смещение — изменение y делим на изменение x.`,
      steps: [
        { type: "plain", text: `Точки (1, 2) и (4, 11)` },
        { type: "note", text: `наклон = (11 &minus; 2) &divide; (4 &minus; 1)` },
        { type: "plain", text: `9 &divide; 3` },
        { type: "result", text: `= 3` },
      ],
      trapHtml: `Частая ошибка — вычесть координаты в разном порядке: например, (11 &minus; 2), но потом (1 &minus; 4) вместо (4 &minus; 1). Всегда вычитайте координаты в одном и том же порядке для x и для y.`,
      whyItMattersHtml: `Наклон измеряет скорость изменения — скорость движения, крутизну склона, темп роста — одну из самых полезных идей в математике и науке.`,
      hintHtml: null,
    },
  },
  {
    slug: "quadratic",
    en: {
      navLabel: `Quadratic Equations`,
      pageTitle: `Quadratic Equations: Solving ax² + bx + c = 0 — Math Practice`,
      metaDescription: `Learn how to solve a quadratic equation by factoring step by step, then practice.`,
      h1: `Quadratic Equations: Solving ax&sup2; + bx + c = 0`,
      hookHtml: `A ball's height follows a rule that equals zero at exactly two moments &mdash; when it's launched and when it lands. If those moments are the solutions to x&sup2; &minus; 5x + 6 = 0, when does the ball leave the ground and when does it land?`,
      ruleHtml: `A <strong>quadratic equation</strong> usually has two answers for x. One way to solve it is to find two numbers that <strong>multiply</strong> to c and <strong>add up</strong> to b, then split the equation into two simple ones.`,
      oneLinerHtml: `In one line: find two numbers that multiply to c and add to b.`,
      steps: [
        { type: "plain", text: `x&sup2; &minus; 5x + 6 = 0` },
        { type: "note", text: `find two numbers that multiply to 6 and add to &minus;5 &rarr; &minus;2 and &minus;3` },
        { type: "plain", text: `(x &minus; 2)(x &minus; 3) = 0` },
        { type: "note", text: `either part can be 0` },
        { type: "plain", text: `x &minus; 2 = 0 &nbsp; or &nbsp; x &minus; 3 = 0` },
        { type: "result", text: `x = 2 &nbsp; or &nbsp; x = 3` },
      ],
      trapHtml: `A common mistake is finding two numbers that multiply correctly but forgetting to check they also add up right &mdash; 1 and 6 multiply to 6, but they add to 7, not &minus;5. Both conditions have to match.`,
      whyItMattersHtml: `Quadratics show up whenever something speeds up or slows down &mdash; thrown balls, braking cars, business profit curves.`,
      hintHtml: `Enter both solutions separated by a comma, e.g. <code>2, 3</code> (either order is fine).`,
    },
    ru: {
      navLabel: `Квадратные уравнения`,
      pageTitle: `Квадратные уравнения: решаем ax² + bx + c = 0 — Практика по математике`,
      metaDescription: `Узнайте, как решить квадратное уравнение разложением на множители, шаг за шагом, а затем потренируйтесь.`,
      h1: `Квадратные уравнения: решаем ax&sup2; + bx + c = 0`,
      hookHtml: `Высота мяча описывается формулой, которая равна нулю ровно в два момента времени — когда его подбросили и когда он приземлился. Если эти моменты — решения уравнения x&sup2; &minus; 5x + 6 = 0, когда мяч покидает землю и когда приземляется?`,
      ruleHtml: `У <strong>квадратного уравнения</strong> обычно два решения для x. Один из способов — найти два числа, которые <strong>перемножаются</strong> в c и <strong>складываются</strong> в b, а затем разбить уравнение на два простых.`,
      oneLinerHtml: `Одной фразой: найдите два числа, которые перемножаются в c и складываются в b.`,
      steps: [
        { type: "plain", text: `x&sup2; &minus; 5x + 6 = 0` },
        { type: "note", text: `ищем два числа, которые дают 6 при умножении и &minus;5 при сложении &rarr; &minus;2 и &minus;3` },
        { type: "plain", text: `(x &minus; 2)(x &minus; 3) = 0` },
        { type: "note", text: `любой из множителей может быть равен 0` },
        { type: "plain", text: `x &minus; 2 = 0 &nbsp; или &nbsp; x &minus; 3 = 0` },
        { type: "result", text: `x = 2 &nbsp; или &nbsp; x = 3` },
      ],
      trapHtml: `Частая ошибка — найти два числа, которые правильно перемножаются, но забыть проверить сумму: 1 и 6 дают 6 при умножении, но в сумме 7, а не &minus;5. Должны совпадать оба условия.`,
      whyItMattersHtml: `Квадратные уравнения появляются везде, где что-то ускоряется или замедляется — брошенные мячи, торможение машины, кривые прибыли в бизнесе.`,
      hintHtml: `Введите оба решения через запятую, например <code>2, 3</code> (порядок не важен).`,
    },
  },
  {
    slug: "parabola",
    en: {
      navLabel: `Parabola`,
      pageTitle: `Parabola: Finding the Vertex — Math Practice`,
      metaDescription: `Learn how to find the vertex of a parabola step by step, then practice.`,
      h1: `Parabola: Finding the Vertex`,
      hookHtml: `A skate ramp's cross-section follows the curve y = x&sup2; &minus; 4x + 1. At what x-position is the very bottom of the ramp?`,
      ruleHtml: `A parabola is the curved graph of y = ax&sup2; + bx + c. Its highest or lowest point, the <strong>vertex</strong>, has an x-value you can find with a simple formula.`,
      oneLinerHtml: `In one line: the vertex sits at x = &minus;b &divide; (2a).`,
      steps: [
        { type: "plain", text: `y = x&sup2; &minus; 4x + 1` },
        { type: "note", text: `x = &minus;b &divide; (2 &times; a) &rarr; &minus;(&minus;4) &divide; (2 &times; 1)` },
        { type: "plain", text: `x = 4 &divide; 2` },
        { type: "result", text: `x = 2` },
      ],
      trapHtml: `A common mistake is forgetting the negative sign on b, or dividing by just "a" instead of "2a" &mdash; both throw off the answer. Write out &minus;b &divide; (2a) fully before plugging in numbers.`,
      whyItMattersHtml: `The vertex tells you the highest or lowest point of anything that follows a curved path &mdash; a thrown object, a satellite dish, a suspension bridge cable.`,
      hintHtml: `Enter just the x-coordinate of the vertex (a whole number).`,
    },
    ru: {
      navLabel: `Парабола`,
      pageTitle: `Парабола: находим вершину — Практика по математике`,
      metaDescription: `Узнайте, как найти вершину параболы, шаг за шагом, а затем потренируйтесь.`,
      h1: `Парабола: находим вершину`,
      hookHtml: `Профиль скейт-рампы описывается кривой y = x&sup2; &minus; 4x + 1. В какой точке x находится самое дно рампы?`,
      ruleHtml: `Парабола — это график вида y = ax&sup2; + bx + c. У её самой высокой или самой низкой точки, <strong>вершины</strong>, координату x можно найти по простой формуле.`,
      oneLinerHtml: `Одной фразой: вершина находится в точке x = &minus;b &divide; (2a).`,
      steps: [
        { type: "plain", text: `y = x&sup2; &minus; 4x + 1` },
        { type: "note", text: `x = &minus;b &divide; (2 &times; a) &rarr; &minus;(&minus;4) &divide; (2 &times; 1)` },
        { type: "plain", text: `x = 4 &divide; 2` },
        { type: "result", text: `x = 2` },
      ],
      trapHtml: `Частая ошибка — забыть минус перед b или разделить только на «a», а не на «2a». Полностью запишите &minus;b &divide; (2a), прежде чем подставлять числа.`,
      whyItMattersHtml: `Вершина показывает самую высокую или низкую точку любого пути, который следует по кривой, — брошенного предмета, спутниковой тарелки, троса подвесного моста.`,
      hintHtml: `Введите только координату x вершины (целое число).`,
    },
  },
  {
    slug: "pythagorean",
    en: {
      navLabel: `Pythagorean Theorem`,
      pageTitle: `Pythagorean Theorem — Math Practice`,
      metaDescription: `Learn the Pythagorean theorem and how to find the hypotenuse step by step, then practice.`,
      h1: `Pythagorean Theorem`,
      hookHtml: `A ladder leans against a wall. Its base is 3 meters from the wall, and it reaches 4 meters up the wall. How long is the ladder?`,
      ruleHtml: `For a right triangle with legs a and b and hypotenuse c: <strong>a&sup2; + b&sup2; = c&sup2;</strong>.`,
      oneLinerHtml: `In one line: square both legs, add them, then take the square root.`,
      steps: [
        { type: "plain", text: `legs 3 and 4` },
        { type: "note", text: `3&sup2; + 4&sup2; = 9 + 16 = 25` },
        { type: "plain", text: `c = &radic;25` },
        { type: "result", text: `c = 5` },
      ],
      trapHtml: `A common mistake is adding the legs first and then squaring &mdash; (3 + 4)&sup2; = 49, not 25. You have to square each leg separately before adding.`,
      whyItMattersHtml: `This is how carpenters check a corner is truly square, and how GPS and screen sizes calculate straight-line distance.`,
      hintHtml: null,
    },
    ru: {
      navLabel: `Теорема Пифагора`,
      pageTitle: `Теорема Пифагора — Практика по математике`,
      metaDescription: `Изучите теорему Пифагора и научитесь находить гипотенузу, шаг за шагом, а затем потренируйтесь.`,
      h1: `Теорема Пифагора`,
      hookHtml: `Лестница прислонена к стене. Её основание находится в 3 метрах от стены, а верх достаёт до высоты 4 метра. Какой длины лестница?`,
      ruleHtml: `Для прямоугольного треугольника с катетами a и b и гипотенузой c: <strong>a&sup2; + b&sup2; = c&sup2;</strong>.`,
      oneLinerHtml: `Одной фразой: возведите оба катета в квадрат, сложите, затем извлеките корень.`,
      steps: [
        { type: "plain", text: `катеты 3 и 4` },
        { type: "note", text: `3&sup2; + 4&sup2; = 9 + 16 = 25` },
        { type: "plain", text: `c = &radic;25` },
        { type: "result", text: `c = 5` },
      ],
      trapHtml: `Частая ошибка — сначала сложить катеты, а потом возвести в квадрат: (3 + 4)&sup2; = 49, а не 25. Каждый катет нужно возвести в квадрат отдельно, а уже потом сложить.`,
      whyItMattersHtml: `Так строители проверяют, действительно ли угол прямой, а GPS и размеры экранов рассчитывают расстояние по прямой.`,
      hintHtml: null,
    },
  },
  {
    slug: "exponents",
    en: {
      navLabel: `Exponents`,
      pageTitle: `Exponents: Repeated Multiplication — Math Practice`,
      metaDescription: `Learn what exponents mean with a simple worked example, then practice.`,
      h1: `Exponents: Repeated Multiplication`,
      hookHtml: `A bacteria colony triples in size every hour. If it starts as 1 and triples 3 times, how big is it?`,
      ruleHtml: `An <strong>exponent</strong> tells you how many times to multiply a number by itself.`,
      oneLinerHtml: `In one line: an exponent means multiply the base by itself, that many times.`,
      steps: [
        { type: "plain", text: `3&sup3; = ?` },
        { type: "note", text: `multiply 3 by itself 3 times` },
        { type: "plain", text: `3 &times; 3 &times; 3` },
        { type: "result", text: `= 27` },
      ],
      trapHtml: `A common mistake is multiplying the base by the exponent instead &mdash; thinking 3&sup3; = 3 &times; 3 = 9. It actually means 3 &times; 3 &times; 3, multiplied three times, not twice.`,
      whyItMattersHtml: `Exponents describe explosive growth &mdash; populations, interest, viral spread &mdash; and are the basis for square roots and scientific notation.`,
      hintHtml: null,
    },
    ru: {
      navLabel: `Степени`,
      pageTitle: `Степени: многократное умножение — Практика по математике`,
      metaDescription: `Узнайте, что означает степень числа, на простом примере, а затем потренируйтесь.`,
      h1: `Степени: многократное умножение`,
      hookHtml: `Колония бактерий утраивается каждый час. Если она начинается с 1 и утраивается 3 раза, какого она станет размера?`,
      ruleHtml: `<strong>Степень</strong> показывает, сколько раз нужно умножить число само на себя.`,
      oneLinerHtml: `Одной фразой: степень значит — умножьте основание само на себя столько раз.`,
      steps: [
        { type: "plain", text: `3&sup3; = ?` },
        { type: "note", text: `умножаем 3 само на себя 3 раза` },
        { type: "plain", text: `3 &times; 3 &times; 3` },
        { type: "result", text: `= 27` },
      ],
      trapHtml: `Частая ошибка — умножить основание на показатель степени: думать, что 3&sup3; = 3 &times; 3 = 9. На самом деле это 3 &times; 3 &times; 3 — три раза, а не два.`,
      whyItMattersHtml: `Степени описывают взрывной рост — рост населения, проценты по вкладу, вирусное распространение — и лежат в основе квадратных корней и научной записи чисел.`,
      hintHtml: null,
    },
  },
  {
    slug: "square-roots",
    en: {
      navLabel: `Square Roots`,
      pageTitle: `Square Roots — Math Practice`,
      metaDescription: `Learn what a square root is with a simple worked example, then practice.`,
      h1: `Square Roots`,
      hookHtml: `You want to build a square garden with an area of 49 square meters. How long should each side be?`,
      ruleHtml: `A <strong>square root</strong> asks &quot;what number, times itself, gives this?&quot; The symbol is &radic;.`,
      oneLinerHtml: `In one line: ask what number times itself gives you this.`,
      steps: [
        { type: "plain", text: `&radic;49 = ?` },
        { type: "note", text: `what number times itself is 49?` },
        { type: "plain", text: `7 &times; 7 = 49` },
        { type: "result", text: `&radic;49 = 7` },
      ],
      trapHtml: `A common mistake is dividing by 2 instead &mdash; thinking &radic;49 means 49 &divide; 2. A square root is about multiplication, not division: find the number that multiplies by itself to reach 49.`,
      whyItMattersHtml: `Square roots undo squaring, and they're the tool behind the Pythagorean theorem and the quadratic formula.`,
      hintHtml: null,
    },
    ru: {
      navLabel: `Квадратный корень`,
      pageTitle: `Квадратный корень — Практика по математике`,
      metaDescription: `Узнайте, что такое квадратный корень, на простом примере, а затем потренируйтесь.`,
      h1: `Квадратный корень`,
      hookHtml: `Вы хотите разбить квадратный сад площадью 49 квадратных метров. Какой длины должна быть каждая сторона?`,
      ruleHtml: `<strong>Квадратный корень</strong> отвечает на вопрос «какое число, умноженное само на себя, даёт это число?». Обозначается символом &radic;.`,
      oneLinerHtml: `Одной фразой: спросите, какое число, умноженное само на себя, даёт это число.`,
      steps: [
        { type: "plain", text: `&radic;49 = ?` },
        { type: "note", text: `какое число, умноженное само на себя, даёт 49?` },
        { type: "plain", text: `7 &times; 7 = 49` },
        { type: "result", text: `&radic;49 = 7` },
      ],
      trapHtml: `Частая ошибка — разделить на 2, думая, что &radic;49 — это 49 &divide; 2. Квадратный корень связан с умножением, а не делением: найдите число, которое при умножении само на себя даёт 49.`,
      whyItMattersHtml: `Квадратный корень — обратная операция к возведению в квадрат, и он лежит в основе теоремы Пифагора и формулы корней квадратного уравнения.`,
      hintHtml: null,
    },
  },
  {
    slug: "absolute-value",
    en: {
      navLabel: `Absolute Value`,
      pageTitle: `Absolute Value — Math Practice`,
      metaDescription: `Learn what absolute value means with a simple worked example, then practice.`,
      h1: `Absolute Value`,
      hookHtml: `The temperature is 7 degrees below freezing (&minus;7&deg;). How far is that from 0 degrees, regardless of direction?`,
      ruleHtml: `<strong>Absolute value</strong> means &quot;distance from 0&quot; &mdash; so it's always positive (or zero), no matter the sign of the number inside.`,
      oneLinerHtml: `In one line: absolute value is just the distance from zero &mdash; always positive.`,
      steps: [
        { type: "plain", text: `|&minus;7| = ?` },
        { type: "note", text: `distance from 0 to &minus;7 is 7` },
        { type: "result", text: `|&minus;7| = 7` },
      ],
      trapHtml: `A common mistake is leaving the answer negative &mdash; writing |&minus;7| = &minus;7. The bars mean "distance," and distance is never negative.`,
      whyItMattersHtml: `Absolute value shows up whenever direction doesn't matter, only size &mdash; how far off a target, how much error, how far below zero.`,
      hintHtml: null,
    },
    ru: {
      navLabel: `Модуль числа`,
      pageTitle: `Модуль числа — Практика по математике`,
      metaDescription: `Узнайте, что такое модуль числа, на простом примере, а затем потренируйтесь.`,
      h1: `Модуль числа`,
      hookHtml: `Температура на 7 градусов ниже нуля (&minus;7&deg;). На сколько это отличается от 0 градусов, независимо от направления?`,
      ruleHtml: `<strong>Модуль числа</strong> означает «расстояние до нуля» — поэтому он всегда положительный (или равен нулю), независимо от знака числа внутри.`,
      oneLinerHtml: `Одной фразой: модуль — это просто расстояние до нуля, всегда положительное.`,
      steps: [
        { type: "plain", text: `|&minus;7| = ?` },
        { type: "note", text: `расстояние от 0 до &minus;7 равно 7` },
        { type: "result", text: `|&minus;7| = 7` },
      ],
      trapHtml: `Частая ошибка — оставить ответ отрицательным: писать |&minus;7| = &minus;7. Модуль означает «расстояние», а расстояние не бывает отрицательным.`,
      whyItMattersHtml: `Модуль числа используется там, где важно не направление, а величина — насколько промахнулись мимо цели, какая погрешность, насколько ниже нуля.`,
      hintHtml: null,
    },
  },
];

module.exports = { SITE_URL, TOPICS };
